GEMINI_API_KEY = "AIzaSyB3hJ4Se5H0kqwU_96pK8MSfJmibF0OSAI"
OPENAI_API_KEY = "sk-u-r74pE82TUEYjFETsavkQ"
OPENAI_BASE_URL = "https://chatwbt3-litellm-app.whitetree-387193cb.westeurope.azurecontainerapps.io/"